GET http://localhost:3001/lanches
###

GET http://localhost:3001/lanches?id=2
###

### Get Lanches by Description
GET http://localhost:3001/lanches/descricao?descricao=Hambúrguer
###

GET http://localhost:3001/login
Content-Type: application/json

{
  "email": "username",
  "senha": "username"
}

// ItemPedido
###
POST http://localhost:3001/itempedido/
Content-Type: application/json

{
  "id_item_do_cardapio": 12,
  "quantidade": 30,
  "observacao": "sem hamburgers"
}

###
DELETE http://localhost:3001/itempedido/4

###
GET http://localhost:3001/itempedido/



###
POST http://localhost:3001/pedido/
Content-Type: application/json
{
  "id_funcionario": 1,
}

###
GET http://localhost:3001/pedido/