### FUNCIONARIO
POST http://localhost:3001/cadastro
Content-Type: application/json

{
  "nome": "Mateus Silverio",
  "email": "silverio123@gmail.com",
  "senha": "admin123"
}


###
POST http://localhost:3001/login
Content-Type: application/json

{
  "email": "",
  "senha": ""
}


### VER CARDAPIO
GET http://localhost:3001/lanches

### CRIAR PEDIDO
POST http://localhost:3001/pedidos
Content-Type: application/json

{
  "id_funcionario": 1,
  "tipo_pedido": "delivery",
  "nome_cliente": "juan",
  "Mesa": null,
  "CEP": "12366940",
  "Status": "em preparação",
  "tipo_pagamento": "PIX"
}

### ADICIONAR ITEM AO PEDIDO
POST http://localhost:3001/itempedido
Content-Type: application/json

{
  "id_pedido": 2,
  "id_item_do_cardapio": 1,
  "quantidade": 2,
  "observacao": "gelada"
}

### CONFIRMAR ITENS DO PEDIDO
GET http://localhost:3001/itempedido
Content-Type: application/json

{
  "id_pedido": 1
}

### CONFIRMAR O PEDIDO
GET http://localhost:3001/pedidos




###
POST http://localhost:3001/lanches
Content-Type: application/json

{
  "nome": "Quarteirão",
  "descricao": "Dois hambúrgueres com cheddar, cebola, picles, ketchup e mostarda no pão com gergelim.",
  "preco": 32.99,
  "disponibilidade": "disponível",
  "imagem": "https://cache-mcd-middleware.mcdonaldscupones.com/media/image/product$kNXwNgUf/200/200/original?country=br",
  "tipo": "hamburguer"
}

###
PUT http://localhost:3001/lanches/update
Content-Type: application/json

{
  "nome_original": "xskibidi",
  "nome": "Batata Individual",
  "descricao": "Porção de batata frita crocante e sequinha, com sal.",
  "preco": 100.00,
  "disponibilidade": "disponível",
  "imagem": "https://i.pinimg.com/736x/e6/73/ca/e673ca8d2a4d99b6b1f1f2e0a6cea4e7.jpg",
  "tipo": "pastel"
}


###
DELETE http://localhost:3001/lanches/delete
Content-Type: application/json

{
  "id": 5
}


###
GET http://localhost:3001/pedidos/CEP
Content-Type: application/json

{
  "CEP": "12366940"
}


###
POST http://localhost:3001/itempedido
Content-Type: application/json

{
  "id_pedido": 6,
  "id_item_do_cardapio": 5,
  "quantidade": 1,
  "observacao": "Sem haburguer"
}

###
GET http://localhost:3001/itempedido
Content-Type: application/json

{
  "id_pedido": 6
}

###
DELETE http://localhost:3001/delete/itempedido
Content-Type: application/json

{
  "id": 6
}

#####


GET http://localhost:3001/lanches/descricao
Content-Type: application/json

{
  "descricao": "Hamburguer"
}

#####
GET http://localhost:3001/pedidos/data
Content-Type: application/json

{
  "filtro": "semana"
}