### FUNCIONARIO
POST http://localhost:3001/cadastro
Content-Type: application/json

{
  "nome": "",
  "email": "",
  "senha": ""
}


###
POST http://localhost:3001/login
Content-Type: application/json

{
  "email": "",
  "senha": ""
}


### VER CARDAPIO
GET http://localhost:3001/lanches

### CRIAR PEDIDO
POST http://localhost:3001/pedidos
Content-Type: application/json

{
  "id_funcionario": 1,
  "tipo_pedido": "delivery",
  "nome_cliente": "henrique",
  "Mesa": null,
  "CEP": "12366940",
  "Status": "em preparação",
  "tipo_pagamento": "PIX"
}

### ADICIONAR ITEM AO PEDIDO
POST http://localhost:3001/itempedido
Content-Type: application/json

{
  "id_pedido": 2,
  "id_item_do_cardapio": 1,
  "quantidade": 2,
  "observacao": "gelada"
}

### CONFIRMAR ITENS DO PEDIDO
GET http://localhost:3001/itempedido
Content-Type: application/json

{
  "id_pedido": 1
}

### CONFIRMAR O PEDIDO
GET http://localhost:3001/pedidos




###
POST http://localhost:3001/lanches
Content-Type: application/json

{
  "nome": "Pastel-Fraqenco",
  "descricao": "FODA",
  "preco": 30.00,
  "disponibilidade": "disponível",
  "imagem": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Hot_dog_with_mustard.png",
  "tipo": "pastel"
  
}

###
PUT http://localhost:3001/lanches/update
Content-Type: application/json

{
  "nome_original": "xskibidi",
  "nome": "xskibidi",
  "descricao": "Skiiiii",
  "preco": 69.00,
  "disponibilidade": "disponível",
  "imagem": "url_da_imagem",
  "tipo": "pastel"
}


###
DELETE http://localhost:3001/lanches/delete
Content-Type: application/json

{
  "id": 1
}


###
GET http://localhost:3001/pedidos/CEP
Content-Type: application/json

{
  "CEP": "12366940"
}


###
POST http://localhost:3001/itempedido
Content-Type: application/json

{
  "id_pedido": 6,
  "id_item_do_cardapio": 5,
  "quantidade": 1,
  "observacao": "Sem haburguer"
}

###
GET http://localhost:3001/itempedido
Content-Type: application/json

{
  "id_pedido": 6
}

###
DELETE http://localhost:3001/delete/itempedido
Content-Type: application/json

{
  "id": 6
}

#####


GET http://localhost:3001/lanches/descricao
Content-Type: application/json

{
  "descricao": "Hamburguer"
}