GET http://localhost:3000/amigo/loiro?api_key=banana

### 

POST http://localhost:3000/amigo
Content-Type: application/json

{
    "name" : "loiro", 
    "adjective" : "nanofilia",
    "weapon" : "ak47"
}


###

PATCH http://localhost:3000/amigo
Content-Type: application/json

{
    "name" : "juan", 
    "newAdjective" : "anticristo(daora)"
}

###
DELETE http://localhost:3000/amigo
Content-Type: application/json

{
    "friend": "undefined"
}